// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB8TloQDPSYLBMe8N1EDjxUyC5A-d-ojk',
    appId: '1:544309714333:web:95a1e24f79149640d4e374',
    messagingSenderId: '544309714333',
    projectId: 'whysup-c9f96',
    authDomain: 'whysup-c9f96.firebaseapp.com',
    storageBucket: 'whysup-c9f96.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1tfytT3jNpUV0_VaxrAcMysqy1Ibn2sA',
    appId: '1:544309714333:android:f78fcc41c169f9bbd4e374',
    messagingSenderId: '544309714333',
    projectId: 'whysup-c9f96',
    storageBucket: 'whysup-c9f96.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgPoYwyY9s47HkhK8sn_Lgsyo0JmjgQfU',
    appId: '1:544309714333:ios:521d4325425d1614d4e374',
    messagingSenderId: '544309714333',
    projectId: 'whysup-c9f96',
    storageBucket: 'whysup-c9f96.firebasestorage.app',
    iosBundleId: 'com.example.whySup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgPoYwyY9s47HkhK8sn_Lgsyo0JmjgQfU',
    appId: '1:544309714333:ios:521d4325425d1614d4e374',
    messagingSenderId: '544309714333',
    projectId: 'whysup-c9f96',
    storageBucket: 'whysup-c9f96.firebasestorage.app',
    iosBundleId: 'com.example.whySup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCB8TloQDPSYLBMe8N1EDjxUyC5A-d-ojk',
    appId: '1:544309714333:web:7ec6d1f55dbb95e7d4e374',
    messagingSenderId: '544309714333',
    projectId: 'whysup-c9f96',
    authDomain: 'whysup-c9f96.firebaseapp.com',
    storageBucket: 'whysup-c9f96.firebasestorage.app',
  );

}